### ISSUE TITLE
Work on erika as input device

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/erika3004#15]

**Comment by ArchibaldBienetre** [comment]
This is about using Erika as a character device. 

Using pyfuse (libfuse) 
* https://pypi.org/project/pyfuse3/
* https://github.com/libfuse/libfuse#libfuse

**Comment by ArchibaldBienetre** [comment]
First steps are there, it seems, e.g. look at this PR: https://github.com/Chaostreff-Potsdam/erika3004/pull/28
