### ISSUE TITLE
Test Arduino sketch on Mini, Nano

### ISSUE THREAD

**Issue by ArchibaldBienetre** [Chaostreff-Potsdam/erika3004#2]
TODO: Test on Mini, Nano

**Comment by cyroxx** [comment]
@sirexeclp Have you tested this at some point? And: Is that still relevant for us?

I would like to close this issue. Since we are rather trying to work with actual USB-to-serial adapters and/or raspi, we won't need Arduino support anymore.

**Comment by sirexeclp** [comment]
I think we tested it at some point, and it didn't work.
