### ISSUE TITLE
Test buck converter on 19V rail as power source for pi

### ISSUE THREAD

**Issue by sirexeclp** [Chaostreff-Potsdam/erika3004#40]

**Comment by ArchibaldBienetre** [comment]
@sirexeclp Was this test a success? Or did you have to give up?

**Comment by sirexeclp** [comment]
Test was successful, my pi zero w is running fine for now, this was actually the requirement to build the internal pi zero.
Running RGB LEDs seems to work as well.
Some more testing could be done, to determine the maximal current we can draw.
