### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by ArchibaldBienetre** [Chaostreff-Potsdam/erika3004#6]
@cyroxx, would you mind getting your changes into the main repo? :) 

https://github.com/cyroxx/erika3004/commit/6ab16835b1619fe668ef53ec94c206fa945d1627

**Comment by cyroxx** [comment]
Done: 2cd763b313a0a2b6f4daa5ed048ecbfaa2337faa
Also added the build status badge to README.
